controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
json_data:
  path: /technology/wendys-working-google-test-ai-powered-drive-thru
  controller: App\Controller\JsonController::index